# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoFiSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for SoFiSearch
  pod 'RevealingSplashView'
  pod 'RxSwift', '~> 4.0'
  pod 'Moya', '~> 4.2'

end
